### PR TITLE
Fixed leak caused by too many new img tags

### LINKED ISSUE #25: Possible memory leak/hang on the electron side
The line `let img = document.createElement("img");` creates a new `img` every time an image is loaded. As far as I can tell, in the current version of MM, the page is never fully reloaded, so those elements just grow and grow. In my experience, WallberryTheme on an rpi3 (I'm using magicmirroros) will stop updating images after several hours at the fastest image update rate (50/hr limited by Unsplash API). I've verified that it's not API limits, and restarting the container (which restarts electron) always fixes it.

(I was using WallberryTheme/Unsplash as a placeholder while working on my own background plugin and I can hang the browser much faster doing the same thing because I have no rate limit. I fixed it by creating one `img` as `this.img` and re-using it.)

### PR DESCRIPTION
**Pull request by samusaran**
Fixes #25

### CODE REVIEW

**Comment by samusaran** [comment]
I could reuse https://github.com/delightedCrow/WallberryTheme/blob/65a1c00d35f0e3c9ea0e0191f82edda33ba93253/WallberryTheme.js#L26 but I don't know if that could affect the theme (i'm not able to test it right now). In theory we could avoid to reassign all the properties to `this.img`, and just assign once to `photoElement `and just change the image `src`.

**Comment by samusaran** [comment]
I'm testing this on a RPi 2B since the day of the pull request, and it's working flawlessy.
No more daily reboot!

**Comment by delightedCrow** [comment]
Awesome! I’ll take a look tomorrow

**Comment by delightedCrow** [comment]
This looks good - can you open this PR against the dev branch?

**Pull request closed without merging**
